apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-kie-springboot
  labels:
    app: openshift-kie-springboot
subjects:
  - kind: ServiceAccount
    name: openshift-kie-springboot
roleRef:
  kind: Role
  name: openshift-kie-springboot
  apiGroup: rbac.authorization.k8s.io