apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: openshift-kie-jdkhttp
  labels:
    app: openshift-kie-jdkhttp
subjects:
  - kind: ServiceAccount
    name: openshift-kie-jdkhttp
roleRef:
  kind: Role
  name: openshift-kie-jdkhttp
  apiGroup: rbac.authorization.k8s.io