apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openshift-kie-thorntail
    version: v1
  name: openshift-kie-thorntail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift-kie-thorntail
      version: v1
  template:
    metadata:
      labels:
        app: openshift-kie-thorntail
        version: v1
    spec:
      containers:
        - env:
          name: openshift-kie-thorntail
          image: <user>/openshift-kie-thorntail:<version>
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:8080/liveness
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - curl
                - localhost:8080/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false